import{a as g,i as l}from"./assets/vendor-C3Ps8wfj.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const p of o.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&s(p)}).observe(document,{childList:!0,subtree:!0});function n(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(r){if(r.ep)return;r.ep=!0;const o=n(r);fetch(r.href,o)}})();const f="49486177-f5d6b48135fe4ab0dc5f3c055",w="https://pixabay.com/api/",E="photo",b="horizontal",L=!0,S=15;console.log(`${f}`);const m=async(e,t=1)=>{try{return(await g.get(w,{params:{key:f,q:e,image_type:E,orientation:b,safesearch:L,per_page:S,page:t}})).data}catch(n){throw console.error("Error fetching images:",n),n}},h=e=>{const t=document.querySelector(".gallery"),n=e.map(s=>`
    <li class="gallery-item">
      <img src="${s.webformatURL}" alt="${s.tags}" />
      <div class="info">
        <p>Likes: ${s.likes}</p>
        <p>Views: ${s.views}</p>
        <p>Comments: ${s.comments}</p>
        <p>Downloads: ${s.downloads}</p>
      </div>
    </li>
  `).join("");t.insertAdjacentHTML("beforeend",n)},P=document.querySelector("#search-form"),q=document.querySelector(".gallery"),u=document.querySelector("#load-more"),i=document.querySelector(".loader");let c="",y=1,d=0,a=0;P.addEventListener("submit",async e=>{if(e.preventDefault(),c=e.target.search.value.trim(),!c){l.error({title:"Error",message:"Please enter a search query!"});return}y=1,d=0,a=0,q.innerHTML="",u.style.display="none",i.style.display="block",await new Promise(t=>setTimeout(t,350));try{const t=await m(c,y);i.style.display="none",d=t.totalHits,a=t.hits.length,t.hits.length===0?l.warning({title:"No Results",message:"Sorry, no images found!",position:"center"}):(h(t.hits),a<d&&(u.style.display="block"))}catch{i.style.display="none",l.error({title:"Error",message:"Failed to fetch images!"})}});u.addEventListener("click",async()=>{y+=1,i.style.display="block",await new Promise(e=>setTimeout(e,350));try{const e=await m(c,y);i.style.display="none",a+=e.hits.length,e.hits.length===0||a>=d?(u.style.display="none",l.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"center"})):(h(e.hits),v())}catch{i.style.display="none",l.error({title:"Error",message:"Failed to fetch images!"})}});function v(){const e=document.querySelector(".gallery-item");if(e){const{height:t}=e.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
